export interface CarData {
  make: string;
  model: string;
  year?: number;
  tier: "common" | "enthusiast" | "premium" | "exotic" | "unicorn";
  horsepower: number;
  country: string;
}

export const CARS_DATABASE: CarData[] = [
  // ──────────── MARUTI SUZUKI ────────────
  { make: "Maruti Suzuki", model: "800", year: 1997, tier: "common", horsepower: 37, country: "India" },
  { make: "Maruti Suzuki", model: "Alto", year: 2000, tier: "common", horsepower: 47, country: "India" },
  { make: "Maruti Suzuki", model: "Alto 800", year: 2023, tier: "common", horsepower: 47, country: "India" },
  { make: "Maruti Suzuki", model: "Alto K10", year: 2023, tier: "common", horsepower: 66, country: "India" },
  { make: "Maruti Suzuki", model: "WagonR", year: 2023, tier: "common", horsepower: 66, country: "India" },
  { make: "Maruti Suzuki", model: "WagonR", year: 2010, tier: "common", horsepower: 67, country: "India" },
  { make: "Maruti Suzuki", model: "Swift", year: 2024, tier: "common", horsepower: 82, country: "India" },
  { make: "Maruti Suzuki", model: "Swift", year: 2018, tier: "common", horsepower: 82, country: "India" },
  { make: "Maruti Suzuki", model: "Swift", year: 2011, tier: "common", horsepower: 86, country: "India" },
  { make: "Maruti Suzuki", model: "Swift", year: 2005, tier: "common", horsepower: 85, country: "India" },
  { make: "Maruti Suzuki", model: "Swift Dzire", year: 2023, tier: "common", horsepower: 82, country: "India" },
  { make: "Maruti Suzuki", model: "Swift Dzire", year: 2017, tier: "common", horsepower: 82, country: "India" },
  { make: "Maruti Suzuki", model: "Dzire", year: 2024, tier: "common", horsepower: 82, country: "India" },
  { make: "Maruti Suzuki", model: "Baleno", year: 2023, tier: "common", horsepower: 89, country: "India" },
  { make: "Maruti Suzuki", model: "Baleno", year: 2019, tier: "common", horsepower: 83, country: "India" },
  { make: "Maruti Suzuki", model: "Celerio", year: 2023, tier: "common", horsepower: 66, country: "India" },
  { make: "Maruti Suzuki", model: "Ciaz", year: 2023, tier: "common", horsepower: 103, country: "India" },
  { make: "Maruti Suzuki", model: "Ciaz", year: 2017, tier: "common", horsepower: 103, country: "India" },
  { make: "Maruti Suzuki", model: "Ignis", year: 2023, tier: "common", horsepower: 82, country: "India" },
  { make: "Maruti Suzuki", model: "S-Presso", year: 2023, tier: "common", horsepower: 66, country: "India" },
  { make: "Maruti Suzuki", model: "Ertiga", year: 2023, tier: "common", horsepower: 103, country: "India" },
  { make: "Maruti Suzuki", model: "Ertiga", year: 2018, tier: "common", horsepower: 103, country: "India" },
  { make: "Maruti Suzuki", model: "XL6", year: 2023, tier: "common", horsepower: 103, country: "India" },
  { make: "Maruti Suzuki", model: "Brezza", year: 2023, tier: "common", horsepower: 103, country: "India" },
  { make: "Maruti Suzuki", model: "Vitara Brezza", year: 2020, tier: "common", horsepower: 103, country: "India" },
  { make: "Maruti Suzuki", model: "Grand Vitara", year: 2023, tier: "common", horsepower: 103, country: "India" },
  { make: "Maruti Suzuki", model: "Fronx", year: 2023, tier: "common", horsepower: 100, country: "India" },
  { make: "Maruti Suzuki", model: "Jimny", year: 2023, tier: "enthusiast", horsepower: 103, country: "India" },
  { make: "Maruti Suzuki", model: "Invicto", year: 2023, tier: "common", horsepower: 186, country: "India" },
  { make: "Maruti Suzuki", model: "Gypsy", year: 2005, tier: "enthusiast", horsepower: 80, country: "India" },
  { make: "Maruti Suzuki", model: "Zen", year: 2004, tier: "common", horsepower: 60, country: "India" },
  { make: "Maruti Suzuki", model: "Zen Carbon / Steel", year: 2003, tier: "enthusiast", horsepower: 60, country: "India" },
  { make: "Maruti Suzuki", model: "Esteem", year: 2004, tier: "common", horsepower: 85, country: "India" },
  { make: "Maruti Suzuki", model: "SX4", year: 2012, tier: "common", horsepower: 103, country: "India" },
  { make: "Maruti Suzuki", model: "Ritz", year: 2014, tier: "common", horsepower: 86, country: "India" },
  { make: "Maruti Suzuki", model: "A-Star", year: 2012, tier: "common", horsepower: 67, country: "India" },
  { make: "Maruti Suzuki", model: "Omni", year: 2010, tier: "common", horsepower: 37, country: "India" },
  { make: "Maruti Suzuki", model: "Eeco", year: 2023, tier: "common", horsepower: 73, country: "India" },
  { make: "Maruti Suzuki", model: "S-Cross", year: 2022, tier: "common", horsepower: 103, country: "India" },
  { make: "Maruti Suzuki", model: "S-Cross 1.6 DDiS", year: 2017, tier: "enthusiast", horsepower: 120, country: "India" },

  // ──────────── HYUNDAI ────────────
  { make: "Hyundai", model: "Santro", year: 2019, tier: "common", horsepower: 68, country: "South Korea" },
  { make: "Hyundai", model: "Santro Xing", year: 2010, tier: "common", horsepower: 63, country: "South Korea" },
  { make: "Hyundai", model: "i10", year: 2016, tier: "common", horsepower: 68, country: "South Korea" },
  { make: "Hyundai", model: "Grand i10", year: 2023, tier: "common", horsepower: 83, country: "South Korea" },
  { make: "Hyundai", model: "Grand i10 Nios", year: 2023, tier: "common", horsepower: 83, country: "South Korea" },
  { make: "Hyundai", model: "i20", year: 2023, tier: "common", horsepower: 113, country: "South Korea" },
  { make: "Hyundai", model: "i20", year: 2018, tier: "common", horsepower: 83, country: "South Korea" },
  { make: "Hyundai", model: "i20", year: 2012, tier: "common", horsepower: 83, country: "South Korea" },
  { make: "Hyundai", model: "i20 N Line", year: 2023, tier: "enthusiast", horsepower: 118, country: "South Korea" },
  { make: "Hyundai", model: "Elite i20", year: 2019, tier: "common", horsepower: 83, country: "South Korea" },
  { make: "Hyundai", model: "Verna", year: 2023, tier: "common", horsepower: 158, country: "South Korea" },
  { make: "Hyundai", model: "Verna 1.5 Turbo", year: 2023, tier: "enthusiast", horsepower: 158, country: "South Korea" },
  { make: "Hyundai", model: "Verna", year: 2020, tier: "common", horsepower: 113, country: "South Korea" },
  { make: "Hyundai", model: "Verna", year: 2017, tier: "common", horsepower: 121, country: "South Korea" },
  { make: "Hyundai", model: "Verna Fluidic", year: 2011, tier: "common", horsepower: 126, country: "South Korea" },
  { make: "Hyundai", model: "Aura", year: 2023, tier: "common", horsepower: 83, country: "South Korea" },
  { make: "Hyundai", model: "Xcent", year: 2019, tier: "common", horsepower: 83, country: "South Korea" },
  { make: "Hyundai", model: "Creta", year: 2024, tier: "common", horsepower: 158, country: "South Korea" },
  { make: "Hyundai", model: "Creta", year: 2020, tier: "common", horsepower: 138, country: "South Korea" },
  { make: "Hyundai", model: "Creta", year: 2017, tier: "common", horsepower: 123, country: "South Korea" },
  { make: "Hyundai", model: "Creta N Line", year: 2024, tier: "enthusiast", horsepower: 158, country: "South Korea" },
  { make: "Hyundai", model: "Venue", year: 2023, tier: "common", horsepower: 118, country: "South Korea" },
  { make: "Hyundai", model: "Venue N Line", year: 2023, tier: "enthusiast", horsepower: 118, country: "South Korea" },
  { make: "Hyundai", model: "Tucson", year: 2023, tier: "common", horsepower: 186, country: "South Korea" },
  { make: "Hyundai", model: "Alcazar", year: 2023, tier: "common", horsepower: 158, country: "South Korea" },
  { make: "Hyundai", model: "Exter", year: 2023, tier: "common", horsepower: 82, country: "South Korea" },
  { make: "Hyundai", model: "Ioniq 5", year: 2023, tier: "premium", horsepower: 217, country: "South Korea" },
  { make: "Hyundai", model: "Kona Electric", year: 2023, tier: "enthusiast", horsepower: 134, country: "South Korea" },
  { make: "Hyundai", model: "Accent", year: 2006, tier: "common", horsepower: 94, country: "South Korea" },
  { make: "Hyundai", model: "Getz", year: 2007, tier: "common", horsepower: 82, country: "South Korea" },
  { make: "Hyundai", model: "Getz Prime 1.5 CRDi", year: 2008, tier: "enthusiast", horsepower: 110, country: "South Korea" },
  { make: "Hyundai", model: "Sonata", year: 2015, tier: "common", horsepower: 198, country: "South Korea" },
  { make: "Hyundai", model: "Santa Fe", year: 2016, tier: "common", horsepower: 194, country: "South Korea" },

  // ──────────── SKODA ────────────
  { make: "Skoda", model: "Slavia", year: 2024, tier: "common", horsepower: 150, country: "Czech Republic" },
  { make: "Skoda", model: "Slavia 1.0 TSI", year: 2023, tier: "common", horsepower: 115, country: "Czech Republic" },
  { make: "Skoda", model: "Slavia 1.5 TSI", year: 2023, tier: "enthusiast", horsepower: 150, country: "Czech Republic" },
  { make: "Skoda", model: "Kushaq", year: 2024, tier: "common", horsepower: 150, country: "Czech Republic" },
  { make: "Skoda", model: "Kushaq 1.5 TSI", year: 2023, tier: "enthusiast", horsepower: 150, country: "Czech Republic" },
  { make: "Skoda", model: "Kushaq Monte Carlo", year: 2023, tier: "enthusiast", horsepower: 150, country: "Czech Republic" },
  { make: "Skoda", model: "Kylaq", year: 2025, tier: "common", horsepower: 115, country: "Czech Republic" },
  { make: "Skoda", model: "Octavia", year: 2023, tier: "common", horsepower: 190, country: "Czech Republic" },
  { make: "Skoda", model: "Octavia RS", year: 2023, tier: "enthusiast", horsepower: 245, country: "Czech Republic" },
  { make: "Skoda", model: "Octavia vRS 230", year: 2017, tier: "enthusiast", horsepower: 230, country: "Czech Republic" },
  { make: "Skoda", model: "Octavia vRS 245", year: 2020, tier: "enthusiast", horsepower: 245, country: "Czech Republic" },
  { make: "Skoda", model: "Octavia (Mk1)", year: 2004, tier: "common", horsepower: 90, country: "Czech Republic" },
  { make: "Skoda", model: "Superb", year: 2024, tier: "premium", horsepower: 190, country: "Czech Republic" },
  { make: "Skoda", model: "Superb", year: 2020, tier: "premium", horsepower: 190, country: "Czech Republic" },
  { make: "Skoda", model: "Kodiaq", year: 2024, tier: "premium", horsepower: 190, country: "Czech Republic" },
  { make: "Skoda", model: "Rapid", year: 2021, tier: "common", horsepower: 110, country: "Czech Republic" },
  { make: "Skoda", model: "Rapid 1.0 TSI", year: 2020, tier: "enthusiast", horsepower: 110, country: "Czech Republic" },
  { make: "Skoda", model: "Fabia", year: 2013, tier: "common", horsepower: 75, country: "Czech Republic" },
  { make: "Skoda", model: "Laura", year: 2012, tier: "common", horsepower: 160, country: "Czech Republic" },
  { make: "Skoda", model: "Laura vRS", year: 2012, tier: "enthusiast", horsepower: 160, country: "Czech Republic" },
  { make: "Skoda", model: "Yeti", year: 2014, tier: "common", horsepower: 110, country: "Czech Republic" },

  // ──────────── VOLKSWAGEN ────────────
  { make: "Volkswagen", model: "Virtus", year: 2024, tier: "common", horsepower: 115, country: "Germany" },
  { make: "Volkswagen", model: "Virtus GT 1.5 TSI", year: 2024, tier: "enthusiast", horsepower: 150, country: "Germany" },
  { make: "Volkswagen", model: "Taigun", year: 2024, tier: "common", horsepower: 115, country: "Germany" },
  { make: "Volkswagen", model: "Taigun GT 1.5 TSI", year: 2024, tier: "enthusiast", horsepower: 150, country: "Germany" },
  { make: "Volkswagen", model: "Polo", year: 2022, tier: "common", horsepower: 76, country: "Germany" },
  { make: "Volkswagen", model: "Polo GT TSI", year: 2021, tier: "enthusiast", horsepower: 110, country: "Germany" },
  { make: "Volkswagen", model: "Polo GT TDI", year: 2019, tier: "enthusiast", horsepower: 110, country: "Germany" },
  { make: "Volkswagen", model: "Polo 1.0 TSI", year: 2021, tier: "enthusiast", horsepower: 110, country: "Germany" },
  { make: "Volkswagen", model: "Polo GTI", year: 2017, tier: "premium", horsepower: 192, country: "Germany" },
  { make: "Volkswagen", model: "Vento", year: 2021, tier: "common", horsepower: 110, country: "Germany" },
  { make: "Volkswagen", model: "Vento TSI", year: 2020, tier: "enthusiast", horsepower: 110, country: "Germany" },
  { make: "Volkswagen", model: "Tiguan", year: 2024, tier: "premium", horsepower: 190, country: "Germany" },
  { make: "Volkswagen", model: "Tiguan Allspace", year: 2021, tier: "premium", horsepower: 190, country: "Germany" },
  { make: "Volkswagen", model: "T-Roc", year: 2021, tier: "enthusiast", horsepower: 150, country: "Germany" },
  { make: "Volkswagen", model: "Jetta", year: 2015, tier: "common", horsepower: 140, country: "Germany" },
  { make: "Volkswagen", model: "Passat", year: 2019, tier: "premium", horsepower: 177, country: "Germany" },
  { make: "Volkswagen", model: "Ameo", year: 2019, tier: "common", horsepower: 76, country: "Germany" },
  { make: "Volkswagen", model: "Beetle", year: 2016, tier: "enthusiast", horsepower: 150, country: "Germany" },

  // ──────────── TATA MOTORS ────────────
  { make: "Tata", model: "Nexon", year: 2024, tier: "common", horsepower: 120, country: "India" },
  { make: "Tata", model: "Nexon EV", year: 2024, tier: "enthusiast", horsepower: 143, country: "India" },
  { make: "Tata", model: "Punch", year: 2024, tier: "common", horsepower: 86, country: "India" },
  { make: "Tata", model: "Punch EV", year: 2024, tier: "common", horsepower: 122, country: "India" },
  { make: "Tata", model: "Tiago", year: 2024, tier: "common", horsepower: 86, country: "India" },
  { make: "Tata", model: "Tiago EV", year: 2024, tier: "common", horsepower: 74, country: "India" },
  { make: "Tata", model: "Tiago JTP", year: 2019, tier: "enthusiast", horsepower: 114, country: "India" },
  { make: "Tata", model: "Tigor", year: 2024, tier: "common", horsepower: 86, country: "India" },
  { make: "Tata", model: "Tigor EV", year: 2024, tier: "common", horsepower: 74, country: "India" },
  { make: "Tata", model: "Tigor JTP", year: 2019, tier: "enthusiast", horsepower: 114, country: "India" },
  { make: "Tata", model: "Altroz", year: 2024, tier: "common", horsepower: 86, country: "India" },
  { make: "Tata", model: "Altroz iTurbo", year: 2023, tier: "enthusiast", horsepower: 110, country: "India" },
  { make: "Tata", model: "Altroz Racer", year: 2024, tier: "enthusiast", horsepower: 120, country: "India" },
  { make: "Tata", model: "Harrier", year: 2024, tier: "common", horsepower: 170, country: "India" },
  { make: "Tata", model: "Safari", year: 2024, tier: "common", horsepower: 170, country: "India" },
  { make: "Tata", model: "Curvv", year: 2024, tier: "common", horsepower: 125, country: "India" },
  { make: "Tata", model: "Curvv EV", year: 2024, tier: "enthusiast", horsepower: 167, country: "India" },
  { make: "Tata", model: "Indica", year: 2005, tier: "common", horsepower: 53, country: "India" },
  { make: "Tata", model: "Indigo", year: 2008, tier: "common", horsepower: 70, country: "India" },
  { make: "Tata", model: "Nano", year: 2012, tier: "common", horsepower: 38, country: "India" },
  { make: "Tata", model: "Hexa", year: 2019, tier: "common", horsepower: 156, country: "India" },
  { make: "Tata", model: "Safari Storme", year: 2018, tier: "enthusiast", horsepower: 156, country: "India" },
  { make: "Tata", model: "Sumo", year: 2010, tier: "common", horsepower: 90, country: "India" },

  // ──────────── MAHINDRA ────────────
  { make: "Mahindra", model: "Thar", year: 2024, tier: "enthusiast", horsepower: 150, country: "India" },
  { make: "Mahindra", model: "Thar Roxx", year: 2024, tier: "enthusiast", horsepower: 175, country: "India" },
  { make: "Mahindra", model: "Thar (Classic CRDe)", year: 2015, tier: "enthusiast", horsepower: 105, country: "India" },
  { make: "Mahindra", model: "Scorpio-N", year: 2024, tier: "common", horsepower: 200, country: "India" },
  { make: "Mahindra", model: "Scorpio Classic", year: 2023, tier: "common", horsepower: 132, country: "India" },
  { make: "Mahindra", model: "Scorpio", year: 2017, tier: "common", horsepower: 140, country: "India" },
  { make: "Mahindra", model: "XUV700", year: 2024, tier: "common", horsepower: 200, country: "India" },
  { make: "Mahindra", model: "XUV500", year: 2020, tier: "common", horsepower: 155, country: "India" },
  { make: "Mahindra", model: "XUV3XO", year: 2024, tier: "common", horsepower: 130, country: "India" },
  { make: "Mahindra", model: "XUV300", year: 2023, tier: "common", horsepower: 110, country: "India" },
  { make: "Mahindra", model: "XUV400 EV", year: 2023, tier: "enthusiast", horsepower: 150, country: "India" },
  { make: "Mahindra", model: "Bolero", year: 2023, tier: "common", horsepower: 76, country: "India" },
  { make: "Mahindra", model: "Bolero Neo", year: 2023, tier: "common", horsepower: 100, country: "India" },
  { make: "Mahindra", model: "Marazzo", year: 2022, tier: "common", horsepower: 122, country: "India" },
  { make: "Mahindra", model: "Xylo", year: 2016, tier: "common", horsepower: 120, country: "India" },
  { make: "Mahindra", model: "BE 6e", year: 2025, tier: "premium", horsepower: 282, country: "India" },
  { make: "Mahindra", model: "XEV 9e", year: 2025, tier: "premium", horsepower: 282, country: "India" },

  // ──────────── TOYOTA ────────────
  { make: "Toyota", model: "Innova Crysta", year: 2023, tier: "common", horsepower: 150, country: "Japan" },
  { make: "Toyota", model: "Innova Hycross", year: 2023, tier: "common", horsepower: 186, country: "Japan" },
  { make: "Toyota", model: "Innova", year: 2015, tier: "common", horsepower: 102, country: "Japan" },
  { make: "Toyota", model: "Fortuner", year: 2024, tier: "common", horsepower: 204, country: "Japan" },
  { make: "Toyota", model: "Fortuner Legender", year: 2023, tier: "enthusiast", horsepower: 204, country: "Japan" },
  { make: "Toyota", model: "Hilux", year: 2023, tier: "enthusiast", horsepower: 204, country: "Japan" },
  { make: "Toyota", model: "Urban Cruiser Hyryder", year: 2023, tier: "common", horsepower: 115, country: "Japan" },
  { make: "Toyota", model: "Glanza", year: 2023, tier: "common", horsepower: 89, country: "Japan" },
  { make: "Toyota", model: "Taisor", year: 2024, tier: "common", horsepower: 100, country: "Japan" },
  { make: "Toyota", model: "Rumion", year: 2023, tier: "common", horsepower: 103, country: "Japan" },
  { make: "Toyota", model: "Corolla Altis", year: 2020, tier: "common", horsepower: 140, country: "Japan" },
  { make: "Toyota", model: "Camry Hybrid", year: 2024, tier: "premium", horsepower: 218, country: "Japan" },
  { make: "Toyota", model: "Etios", year: 2018, tier: "common", horsepower: 90, country: "Japan" },
  { make: "Toyota", model: "Etios Liva", year: 2018, tier: "common", horsepower: 80, country: "Japan" },
  { make: "Toyota", model: "Land Cruiser 300", year: 2024, tier: "premium", horsepower: 309, country: "Japan" },
  { make: "Toyota", model: "Vellfire", year: 2024, tier: "premium", horsepower: 193, country: "Japan" },

  // ──────────── HONDA ────────────
  { make: "Honda", model: "City", year: 2024, tier: "common", horsepower: 121, country: "Japan" },
  { make: "Honda", model: "City e:HEV (Hybrid)", year: 2023, tier: "common", horsepower: 126, country: "Japan" },
  { make: "Honda", model: "City (4th Gen)", year: 2019, tier: "common", horsepower: 119, country: "Japan" },
  { make: "Honda", model: "City (3rd Gen)", year: 2013, tier: "common", horsepower: 118, country: "Japan" },
  { make: "Honda", model: "City (Type 2 VTEC)", year: 2003, tier: "enthusiast", horsepower: 106, country: "Japan" },
  { make: "Honda", model: "Elevate", year: 2024, tier: "common", horsepower: 121, country: "Japan" },
  { make: "Honda", model: "Amaze", year: 2024, tier: "common", horsepower: 90, country: "Japan" },
  { make: "Honda", model: "Jazz", year: 2021, tier: "common", horsepower: 90, country: "Japan" },
  { make: "Honda", model: "WR-V", year: 2021, tier: "common", horsepower: 90, country: "Japan" },
  { make: "Honda", model: "Civic", year: 2020, tier: "common", horsepower: 141, country: "Japan" },
  { make: "Honda", model: "Civic (8th Gen)", year: 2010, tier: "enthusiast", horsepower: 132, country: "Japan" },
  { make: "Honda", model: "Accord", year: 2016, tier: "common", horsepower: 180, country: "Japan" },
  { make: "Honda", model: "Accord V6", year: 2010, tier: "enthusiast", horsepower: 275, country: "Japan" },
  { make: "Honda", model: "CR-V", year: 2019, tier: "common", horsepower: 154, country: "Japan" },
  { make: "Honda", model: "Brio", year: 2016, tier: "common", horsepower: 88, country: "Japan" },

  // ──────────── KIA ────────────
  { make: "Kia", model: "Seltos", year: 2024, tier: "common", horsepower: 160, country: "South Korea" },
  { make: "Kia", model: "Seltos GT Line / X-Line", year: 2024, tier: "enthusiast", horsepower: 160, country: "South Korea" },
  { make: "Kia", model: "Sonet", year: 2024, tier: "common", horsepower: 120, country: "South Korea" },
  { make: "Kia", model: "Carens", year: 2024, tier: "common", horsepower: 160, country: "South Korea" },
  { make: "Kia", model: "Carnival", year: 2024, tier: "premium", horsepower: 193, country: "South Korea" },
  { make: "Kia", model: "EV6", year: 2023, tier: "premium", horsepower: 325, country: "South Korea" },
  { make: "Kia", model: "EV9", year: 2024, tier: "premium", horsepower: 384, country: "South Korea" },

  // ──────────── MG MOTOR ────────────
  { make: "MG", model: "Hector", year: 2024, tier: "common", horsepower: 143, country: "UK" },
  { make: "MG", model: "Hector Plus", year: 2023, tier: "common", horsepower: 143, country: "UK" },
  { make: "MG", model: "Astor", year: 2023, tier: "common", horsepower: 140, country: "UK" },
  { make: "MG", model: "ZS EV", year: 2023, tier: "enthusiast", horsepower: 177, country: "UK" },
  { make: "MG", model: "Comet EV", year: 2023, tier: "common", horsepower: 42, country: "UK" },
  { make: "MG", model: "Windsor EV", year: 2024, tier: "common", horsepower: 136, country: "UK" },
  { make: "MG", model: "Gloster", year: 2023, tier: "premium", horsepower: 218, country: "UK" },

  // ──────────── FORD (India) ────────────
  { make: "Ford", model: "EcoSport", year: 2021, tier: "common", horsepower: 123, country: "USA" },
  { make: "Ford", model: "EcoSport 1.0 EcoBoost", year: 2019, tier: "enthusiast", horsepower: 125, country: "USA" },
  { make: "Ford", model: "Endeavour 3.2", year: 2019, tier: "enthusiast", horsepower: 200, country: "USA" },
  { make: "Ford", model: "Endeavour 2.0", year: 2021, tier: "common", horsepower: 170, country: "USA" },
  { make: "Ford", model: "Figo", year: 2020, tier: "common", horsepower: 96, country: "USA" },
  { make: "Ford", model: "Figo 1.5 TDCi", year: 2019, tier: "enthusiast", horsepower: 100, country: "USA" },
  { make: "Ford", model: "Figo 1.5 AT (123hp)", year: 2019, tier: "enthusiast", horsepower: 123, country: "USA" },
  { make: "Ford", model: "Aspire", year: 2021, tier: "common", horsepower: 96, country: "USA" },
  { make: "Ford", model: "Freestyle", year: 2021, tier: "common", horsepower: 96, country: "USA" },
  { make: "Ford", model: "Mustang GT 5.0", year: 2019, tier: "premium", horsepower: 401, country: "USA" },
  { make: "Ford", model: "Fiesta 1.6S", year: 2010, tier: "enthusiast", horsepower: 101, country: "USA" },
  { make: "Ford", model: "Ikon 1.6 Josh", year: 2005, tier: "enthusiast", horsepower: 92, country: "USA" },

  // ──────────── CHEVROLET ────────────
  { make: "Chevrolet", model: "Cruze", year: 2016, tier: "enthusiast", horsepower: 166, country: "USA" },
  { make: "Chevrolet", model: "Beat", year: 2017, tier: "common", horsepower: 79, country: "USA" },
  { make: "Chevrolet", model: "Beat Diesel", year: 2016, tier: "common", horsepower: 58, country: "USA" },
  { make: "Chevrolet", model: "Optra Magnum 2.0 TCDi", year: 2010, tier: "enthusiast", horsepower: 120, country: "USA" },
  { make: "Chevrolet", model: "Tavera", year: 2015, tier: "common", horsepower: 80, country: "USA" },
  { make: "Chevrolet", model: "Spark", year: 2012, tier: "common", horsepower: 63, country: "USA" },

  // ──────────── FIAT ────────────
  { make: "Fiat", model: "Punto Abarth", year: 2017, tier: "enthusiast", horsepower: 145, country: "Italy" },
  { make: "Fiat", model: "Avventura Abarth", year: 2017, tier: "enthusiast", horsepower: 140, country: "Italy" },
  { make: "Fiat", model: "Linea 1.4 T-Jet", year: 2015, tier: "enthusiast", horsepower: 125, country: "Italy" },
  { make: "Fiat", model: "Grande Punto 90hp", year: 2014, tier: "enthusiast", horsepower: 93, country: "Italy" },
  { make: "Fiat", model: "Palio 1.6 GTX", year: 2004, tier: "enthusiast", horsepower: 100, country: "Italy" },
  { make: "Fiat", model: "Palio 1.2", year: 2005, tier: "common", horsepower: 73, country: "Italy" },
  { make: "Fiat", model: "Uno", year: 2000, tier: "common", horsepower: 45, country: "Italy" },

  // ──────────── RENAULT / NISSAN ────────────
  { make: "Renault", model: "Duster", year: 2019, tier: "common", horsepower: 110, country: "France" },
  { make: "Renault", model: "Duster 1.3 Turbo", year: 2021, tier: "enthusiast", horsepower: 156, country: "France" },
  { make: "Renault", model: "Kwid", year: 2023, tier: "common", horsepower: 68, country: "France" },
  { make: "Renault", model: "Kiger", year: 2023, tier: "common", horsepower: 100, country: "France" },
  { make: "Renault", model: "Triber", year: 2023, tier: "common", horsepower: 72, country: "France" },
  { make: "Nissan", model: "Magnite", year: 2024, tier: "common", horsepower: 100, country: "Japan" },
  { make: "Nissan", model: "Terrano", year: 2018, tier: "common", horsepower: 110, country: "Japan" },
  { make: "Nissan", model: "Micra Active", year: 2019, tier: "common", horsepower: 68, country: "Japan" },
  { make: "Nissan", model: "Sunny", year: 2017, tier: "common", horsepower: 99, country: "Japan" },
  { make: "Nissan", model: "GT-R (R35)", year: 2020, tier: "premium", horsepower: 570, country: "Japan" },

  // ──────────── JEEP ────────────
  { make: "Jeep", model: "Compass", year: 2024, tier: "common", horsepower: 170, country: "USA" },
  { make: "Jeep", model: "Compass Trailhawk", year: 2022, tier: "enthusiast", horsepower: 170, country: "USA" },
  { make: "Jeep", model: "Meridian", year: 2024, tier: "common", horsepower: 170, country: "USA" },
  { make: "Jeep", model: "Wrangler Rubicon", year: 2024, tier: "enthusiast", horsepower: 272, country: "USA" },
  { make: "Jeep", model: "Grand Cherokee", year: 2024, tier: "premium", horsepower: 272, country: "USA" },

  // ──────────── LUXURY GERMAN & BRITISH (India) ────────────
  { make: "BMW", model: "3 Series Gran Limousine (330Li)", year: 2024, tier: "premium", horsepower: 258, country: "Germany" },
  { make: "BMW", model: "M340i xDrive", year: 2024, tier: "premium", horsepower: 382, country: "Germany" },
  { make: "BMW", model: "2 Series Gran Coupe (220i)", year: 2023, tier: "premium", horsepower: 192, country: "Germany" },
  { make: "BMW", model: "5 Series LWB (530Li)", year: 2024, tier: "premium", horsepower: 258, country: "Germany" },
  { make: "BMW", model: "530d", year: 2022, tier: "premium", horsepower: 265, country: "Germany" },
  { make: "BMW", model: "X1", year: 2024, tier: "premium", horsepower: 150, country: "Germany" },
  { make: "BMW", model: "X3 (xDrive20d / 30i)", year: 2023, tier: "premium", horsepower: 252, country: "Germany" },
  { make: "BMW", model: "X5", year: 2024, tier: "premium", horsepower: 381, country: "Germany" },
  { make: "BMW", model: "X7", year: 2024, tier: "exotic", horsepower: 381, country: "Germany" },
  { make: "BMW", model: "M2", year: 2024, tier: "premium", horsepower: 460, country: "Germany" },
  { make: "BMW", model: "M3 Competition", year: 2024, tier: "premium", horsepower: 510, country: "Germany" },
  { make: "BMW", model: "M4 Competition", year: 2024, tier: "premium", horsepower: 510, country: "Germany" },
  { make: "BMW", model: "M5 Competition", year: 2023, tier: "exotic", horsepower: 625, country: "Germany" },
  { make: "BMW", model: "iX1", year: 2024, tier: "premium", horsepower: 313, country: "Germany" },
  { make: "BMW", model: "i4", year: 2024, tier: "premium", horsepower: 340, country: "Germany" },
  { make: "BMW", model: "iX", year: 2024, tier: "exotic", horsepower: 326, country: "Germany" },
  { make: "BMW", model: "i7", year: 2024, tier: "exotic", horsepower: 544, country: "Germany" },
  { make: "BMW", model: "Z4 M40i", year: 2024, tier: "premium", horsepower: 340, country: "Germany" },

  { make: "Mercedes-Benz", model: "A-Class Limousine (A200)", year: 2023, tier: "premium", horsepower: 163, country: "Germany" },
  { make: "Mercedes-Benz", model: "C-Class (C200 / C220d)", year: 2024, tier: "premium", horsepower: 204, country: "Germany" },
  { make: "Mercedes-Benz", model: "E-Class (E200 / E220d / E350d)", year: 2024, tier: "premium", horsepower: 197, country: "Germany" },
  { make: "Mercedes-Benz", model: "S-Class (S350d / S450)", year: 2024, tier: "exotic", horsepower: 367, country: "Germany" },
  { make: "Mercedes-Benz", model: "GLA", year: 2024, tier: "premium", horsepower: 163, country: "Germany" },
  { make: "Mercedes-Benz", model: "GLC", year: 2024, tier: "premium", horsepower: 204, country: "Germany" },
  { make: "Mercedes-Benz", model: "GLE", year: 2024, tier: "premium", horsepower: 269, country: "Germany" },
  { make: "Mercedes-Benz", model: "GLS", year: 2024, tier: "exotic", horsepower: 381, country: "Germany" },
  { make: "Mercedes-Benz", model: "G-Class G63 AMG", year: 2024, tier: "exotic", horsepower: 585, country: "Germany" },
  { make: "Mercedes-Benz", model: "G400d", year: 2023, tier: "exotic", horsepower: 330, country: "Germany" },
  { make: "Mercedes-AMG", model: "A45 S", year: 2024, tier: "premium", horsepower: 421, country: "Germany" },
  { make: "Mercedes-AMG", model: "C43", year: 2024, tier: "premium", horsepower: 408, country: "Germany" },
  { make: "Mercedes-AMG", model: "C63 S E-Performance", year: 2024, tier: "premium", horsepower: 680, country: "Germany" },
  { make: "Mercedes-AMG", model: "GT 63 S 4-Door", year: 2024, tier: "exotic", horsepower: 639, country: "Germany" },
  { make: "Mercedes-Benz", model: "Maybach S580 / S680", year: 2024, tier: "unicorn", horsepower: 612, country: "Germany" },
  { make: "Mercedes-Benz", model: "Maybach GLS 600", year: 2024, tier: "unicorn", horsepower: 557, country: "Germany" },

  { make: "Audi", model: "A4 (40 TFSI)", year: 2024, tier: "premium", horsepower: 204, country: "Germany" },
  { make: "Audi", model: "A6 (45 TFSI)", year: 2024, tier: "premium", horsepower: 245, country: "Germany" },
  { make: "Audi", model: "A8 L", year: 2024, tier: "exotic", horsepower: 340, country: "Germany" },
  { make: "Audi", model: "Q3", year: 2024, tier: "premium", horsepower: 190, country: "Germany" },
  { make: "Audi", model: "Q3 Sportback", year: 2024, tier: "premium", horsepower: 190, country: "Germany" },
  { make: "Audi", model: "Q5", year: 2024, tier: "premium", horsepower: 249, country: "Germany" },
  { make: "Audi", model: "Q7", year: 2024, tier: "premium", horsepower: 340, country: "Germany" },
  { make: "Audi", model: "Q8", year: 2024, tier: "exotic", horsepower: 340, country: "Germany" },
  { make: "Audi", model: "RS5 Sportback", year: 2023, tier: "premium", horsepower: 450, country: "Germany" },
  { make: "Audi", model: "RS e-tron GT", year: 2024, tier: "exotic", horsepower: 646, country: "Germany" },
  { make: "Audi", model: "R8 V10", year: 2020, tier: "exotic", horsepower: 610, country: "Germany" },

  { make: "Land Rover", model: "Defender 110", year: 2024, tier: "premium", horsepower: 300, country: "UK" },
  { make: "Land Rover", model: "Defender 90", year: 2024, tier: "premium", horsepower: 300, country: "UK" },
  { make: "Land Rover", model: "Defender 130", year: 2024, tier: "premium", horsepower: 300, country: "UK" },
  { make: "Land Rover", model: "Range Rover", year: 2024, tier: "exotic", horsepower: 400, country: "UK" },
  { make: "Land Rover", model: "Range Rover Sport", year: 2024, tier: "exotic", horsepower: 400, country: "UK" },
  { make: "Land Rover", model: "Range Rover Velar", year: 2024, tier: "premium", horsepower: 250, country: "UK" },
  { make: "Land Rover", model: "Range Rover Evoque", year: 2024, tier: "premium", horsepower: 250, country: "UK" },
  { make: "Land Rover", model: "Discovery", year: 2024, tier: "premium", horsepower: 300, country: "UK" },
  { make: "Jaguar", model: "F-Pace", year: 2024, tier: "premium", horsepower: 250, country: "UK" },
  { make: "Jaguar", model: "F-Type", year: 2023, tier: "premium", horsepower: 300, country: "UK" },
  { make: "Jaguar", model: "XF", year: 2023, tier: "premium", horsepower: 250, country: "UK" },

  { make: "Volvo", model: "XC40", year: 2023, tier: "premium", horsepower: 197, country: "Sweden" },
  { make: "Volvo", model: "XC40 Recharge (EX40)", year: 2024, tier: "premium", horsepower: 408, country: "Sweden" },
  { make: "Volvo", model: "C40 Recharge (EC40)", year: 2024, tier: "premium", horsepower: 408, country: "Sweden" },
  { make: "Volvo", model: "XC60", year: 2024, tier: "premium", horsepower: 250, country: "Sweden" },
  { make: "Volvo", model: "XC90", year: 2024, tier: "premium", horsepower: 300, country: "Sweden" },
  { make: "Volvo", model: "S90", year: 2024, tier: "premium", horsepower: 250, country: "Sweden" },

  { make: "Porsche", model: "911 Carrera", year: 2024, tier: "exotic", horsepower: 385, country: "Germany" },
  { make: "Porsche", model: "911 GT3", year: 2024, tier: "exotic", horsepower: 510, country: "Germany" },
  { make: "Porsche", model: "911 Turbo S", year: 2024, tier: "exotic", horsepower: 650, country: "Germany" },
  { make: "Porsche", model: "718 Cayman", year: 2024, tier: "premium", horsepower: 300, country: "Germany" },
  { make: "Porsche", model: "718 Boxster", year: 2024, tier: "premium", horsepower: 300, country: "Germany" },
  { make: "Porsche", model: "718 Cayman GT4 RS", year: 2024, tier: "exotic", horsepower: 500, country: "Germany" },
  { make: "Porsche", model: "Macan", year: 2024, tier: "premium", horsepower: 265, country: "Germany" },
  { make: "Porsche", model: "Cayenne", year: 2024, tier: "exotic", horsepower: 353, country: "Germany" },
  { make: "Porsche", model: "Panamera", year: 2024, tier: "exotic", horsepower: 353, country: "Germany" },
  { make: "Porsche", model: "Taycan", year: 2024, tier: "exotic", horsepower: 408, country: "Germany" },

  // ──────────── SUPER & HYPERCARS (Exotics & Unicorns) ────────────
  { make: "Lamborghini", model: "Urus", year: 2024, tier: "exotic", horsepower: 666, country: "Italy" },
  { make: "Lamborghini", model: "Huracan Evo", year: 2023, tier: "exotic", horsepower: 640, country: "Italy" },
  { make: "Lamborghini", model: "Huracan STO", year: 2023, tier: "exotic", horsepower: 640, country: "Italy" },
  { make: "Lamborghini", model: "Huracan Tecnica", year: 2024, tier: "exotic", horsepower: 640, country: "Italy" },
  { make: "Lamborghini", model: "Revuelto", year: 2024, tier: "unicorn", horsepower: 1015, country: "Italy" },
  { make: "Lamborghini", model: "Aventador SVJ", year: 2021, tier: "unicorn", horsepower: 770, country: "Italy" },
  { make: "Ferrari", model: "296 GTB", year: 2024, tier: "unicorn", horsepower: 830, country: "Italy" },
  { make: "Ferrari", model: "Roma", year: 2024, tier: "exotic", horsepower: 620, country: "Italy" },
  { make: "Ferrari", model: "Purosangue", year: 2024, tier: "unicorn", horsepower: 725, country: "Italy" },
  { make: "Ferrari", model: "SF90 Stradale", year: 2024, tier: "unicorn", horsepower: 1000, country: "Italy" },
  { make: "Ferrari", model: "F8 Tributo", year: 2022, tier: "exotic", horsepower: 720, country: "Italy" },
  { make: "Ferrari", model: "488 GTB", year: 2019, tier: "exotic", horsepower: 670, country: "Italy" },
  { make: "Ferrari", model: "458 Italia", year: 2015, tier: "exotic", horsepower: 570, country: "Italy" },
  { make: "Ferrari", model: "LaFerrari", year: 2015, tier: "unicorn", horsepower: 963, country: "Italy" },
  { make: "McLaren", model: "720S", year: 2023, tier: "exotic", horsepower: 720, country: "UK" },
  { make: "McLaren", model: "750S", year: 2024, tier: "exotic", horsepower: 750, country: "UK" },
  { make: "McLaren", model: "Artura", year: 2024, tier: "exotic", horsepower: 680, country: "UK" },
  { make: "McLaren", model: "GT", year: 2023, tier: "exotic", horsepower: 620, country: "UK" },
  { make: "McLaren", model: "P1", year: 2015, tier: "unicorn", horsepower: 916, country: "UK" },
  { make: "Aston Martin", model: "Vantage", year: 2024, tier: "exotic", horsepower: 665, country: "UK" },
  { make: "Aston Martin", model: "DB12", year: 2024, tier: "exotic", horsepower: 680, country: "UK" },
  { make: "Aston Martin", model: "DBX 707", year: 2024, tier: "exotic", horsepower: 707, country: "UK" },
  { make: "Rolls-Royce", model: "Ghost", year: 2024, tier: "unicorn", horsepower: 571, country: "UK" },
  { make: "Rolls-Royce", model: "Cullinan", year: 2024, tier: "unicorn", horsepower: 571, country: "UK" },
  { make: "Rolls-Royce", model: "Phantom VIII", year: 2024, tier: "unicorn", horsepower: 571, country: "UK" },
  { make: "Rolls-Royce", model: "Spectre", year: 2024, tier: "unicorn", horsepower: 585, country: "UK" },
  { make: "Bentley", model: "Continental GT", year: 2024, tier: "unicorn", horsepower: 550, country: "UK" },
  { make: "Bentley", model: "Flying Spur", year: 2024, tier: "unicorn", horsepower: 550, country: "UK" },
  { make: "Bentley", model: "Bentayga", year: 2024, tier: "unicorn", horsepower: 550, country: "UK" },
  { make: "Bugatti", model: "Chiron", year: 2023, tier: "unicorn", horsepower: 1500, country: "France" },
  { make: "Bugatti", model: "Veyron", year: 2015, tier: "unicorn", horsepower: 1001, country: "France" },
  { make: "Koenigsegg", model: "Jesko", year: 2023, tier: "unicorn", horsepower: 1600, country: "Sweden" },
  { make: "Pagani", model: "Huayra", year: 2022, tier: "unicorn", horsepower: 764, country: "Italy" },
  { make: "Rimac", model: "Nevera", year: 2023, tier: "unicorn", horsepower: 1914, country: "Croatia" },

  // ──────────── INDIAN CLASSICS ────────────
  { make: "Hindustan Motors", model: "Ambassador", year: 2005, tier: "common", horsepower: 75, country: "India" },
  { make: "Premier", model: "Padmini", year: 1998, tier: "common", horsepower: 48, country: "India" },
  { make: "Hindustan Motors", model: "Contessa", year: 2002, tier: "enthusiast", horsepower: 75, country: "India" },
  { make: "Maruti Suzuki", model: "1000", year: 2000, tier: "common", horsepower: 46, country: "India" },
  { make: "Standard", model: "Herald", year: 1975, tier: "common", horsepower: 39, country: "India" },

  // ──────────── MIDDLE EAST / DUBAI / GCC POPULAR ────────────
  // Popular GCC SUVs & Trucks
  { make: "Nissan", model: "Patrol", year: 2024, tier: "premium", horsepower: 400, country: "Japan" },
  { make: "Nissan", model: "Patrol Nismo", year: 2024, tier: "enthusiast", horsepower: 428, country: "Japan" },
  { make: "Nissan", model: "Patrol Safari (Super Safari)", year: 2023, tier: "enthusiast", horsepower: 280, country: "Japan" },
  { make: "Toyota", model: "Land Cruiser 300", year: 2024, tier: "premium", horsepower: 409, country: "Japan" },
  { make: "Toyota", model: "Land Cruiser Prado", year: 2024, tier: "premium", horsepower: 281, country: "Japan" },
  { make: "Toyota", model: "Land Cruiser 70 Series", year: 2024, tier: "enthusiast", horsepower: 228, country: "Japan" },
  { make: "Toyota", model: "FJ Cruiser", year: 2023, tier: "enthusiast", horsepower: 270, country: "Japan" },
  { make: "Toyota", model: "Hilux", year: 2024, tier: "common", horsepower: 204, country: "Japan" },
  { make: "Mitsubishi", model: "Pajero", year: 2021, tier: "common", horsepower: 250, country: "Japan" },
  { make: "Mitsubishi", model: "Outlander", year: 2024, tier: "common", horsepower: 181, country: "Japan" },
  { make: "Mitsubishi", model: "L200", year: 2024, tier: "common", horsepower: 181, country: "Japan" },
  { make: "Nissan", model: "Pathfinder", year: 2024, tier: "common", horsepower: 284, country: "Japan" },
  { make: "Nissan", model: "X-Terra", year: 2024, tier: "common", horsepower: 165, country: "Japan" },
  { make: "Nissan", model: "Navara", year: 2024, tier: "common", horsepower: 190, country: "Japan" },

  // GCC Luxury SUVs
  { make: "Lexus", model: "LX600", year: 2024, tier: "exotic", horsepower: 409, country: "Japan" },
  { make: "Lexus", model: "LX570", year: 2021, tier: "exotic", horsepower: 383, country: "Japan" },
  { make: "Lexus", model: "GX460", year: 2023, tier: "premium", horsepower: 301, country: "Japan" },
  { make: "Lexus", model: "GX550", year: 2024, tier: "premium", horsepower: 349, country: "Japan" },
  { make: "Lexus", model: "RX350", year: 2024, tier: "premium", horsepower: 275, country: "Japan" },
  { make: "Lexus", model: "NX350", year: 2024, tier: "premium", horsepower: 275, country: "Japan" },
  { make: "Lexus", model: "ES350", year: 2024, tier: "premium", horsepower: 302, country: "Japan" },
  { make: "Lexus", model: "IS350", year: 2024, tier: "premium", horsepower: 311, country: "Japan" },
  { make: "Lexus", model: "LC500", year: 2024, tier: "exotic", horsepower: 471, country: "Japan" },
  { make: "Infiniti", model: "QX80", year: 2024, tier: "premium", horsepower: 450, country: "Japan" },
  { make: "Infiniti", model: "QX60", year: 2024, tier: "premium", horsepower: 295, country: "Japan" },
  { make: "Infiniti", model: "QX50", year: 2024, tier: "premium", horsepower: 268, country: "Japan" },
  { make: "Infiniti", model: "Q50", year: 2024, tier: "enthusiast", horsepower: 300, country: "Japan" },
  { make: "Cadillac", model: "Escalade", year: 2024, tier: "exotic", horsepower: 420, country: "USA" },
  { make: "Cadillac", model: "Escalade-V", year: 2024, tier: "exotic", horsepower: 682, country: "USA" },
  { make: "GMC", model: "Yukon Denali", year: 2024, tier: "premium", horsepower: 420, country: "USA" },
  { make: "GMC", model: "Sierra 1500", year: 2024, tier: "premium", horsepower: 420, country: "USA" },
  { make: "Chevrolet", model: "Tahoe", year: 2024, tier: "premium", horsepower: 355, country: "USA" },
  { make: "Chevrolet", model: "Suburban", year: 2024, tier: "premium", horsepower: 355, country: "USA" },
  { make: "Chevrolet", model: "Silverado", year: 2024, tier: "premium", horsepower: 420, country: "USA" },
  { make: "Lincoln", model: "Navigator", year: 2024, tier: "exotic", horsepower: 440, country: "USA" },
  { make: "Genesis", model: "GV80", year: 2024, tier: "premium", horsepower: 375, country: "South Korea" },
  { make: "Genesis", model: "G80", year: 2024, tier: "premium", horsepower: 375, country: "South Korea" },
  { make: "Genesis", model: "G90", year: 2024, tier: "exotic", horsepower: 409, country: "South Korea" },

  // GCC Muscle & American Sedans
  { make: "Dodge", model: "Charger Hellcat", year: 2023, tier: "exotic", horsepower: 717, country: "USA" },
  { make: "Dodge", model: "Challenger Hellcat", year: 2023, tier: "exotic", horsepower: 717, country: "USA" },
  { make: "Dodge", model: "Durango SRT Hellcat", year: 2024, tier: "exotic", horsepower: 710, country: "USA" },
  { make: "Chrysler", model: "300C", year: 2023, tier: "enthusiast", horsepower: 485, country: "USA" },
  { make: "Ford", model: "F-150 Raptor", year: 2024, tier: "enthusiast", horsepower: 450, country: "USA" },
  { make: "RAM", model: "1500 TRX", year: 2024, tier: "exotic", horsepower: 702, country: "USA" },

  // Daily Drivers Popular in Dubai/GCC
  { make: "Toyota", model: "Camry", year: 2024, tier: "common", horsepower: 203, country: "Japan" },
  { make: "Toyota", model: "Corolla", year: 2024, tier: "common", horsepower: 169, country: "Japan" },
  { make: "Toyota", model: "Yaris Sedan", year: 2024, tier: "common", horsepower: 105, country: "Japan" },
  { make: "Toyota", model: "Crown", year: 2024, tier: "premium", horsepower: 340, country: "Japan" },
  { make: "Toyota", model: "RAV4", year: 2024, tier: "common", horsepower: 203, country: "Japan" },
  { make: "Nissan", model: "Altima", year: 2024, tier: "common", horsepower: 188, country: "Japan" },
  { make: "Nissan", model: "Maxima", year: 2023, tier: "enthusiast", horsepower: 300, country: "Japan" },
  { make: "Nissan", model: "Sunny", year: 2024, tier: "common", horsepower: 118, country: "Japan" },
  { make: "Nissan", model: "Kicks", year: 2024, tier: "common", horsepower: 122, country: "Japan" },
  { make: "Honda", model: "Accord", year: 2024, tier: "common", horsepower: 192, country: "Japan" },
  { make: "Honda", model: "Civic", year: 2024, tier: "common", horsepower: 158, country: "Japan" },
  { make: "Honda", model: "Pilot", year: 2024, tier: "common", horsepower: 285, country: "Japan" },
  { make: "Hyundai", model: "Sonata", year: 2024, tier: "common", horsepower: 191, country: "South Korea" },
  { make: "Hyundai", model: "Elantra", year: 2024, tier: "common", horsepower: 147, country: "South Korea" },
  { make: "Hyundai", model: "Palisade", year: 2024, tier: "premium", horsepower: 291, country: "South Korea" },
  { make: "Hyundai", model: "Accent", year: 2024, tier: "common", horsepower: 120, country: "South Korea" },
  { make: "Kia", model: "K5", year: 2024, tier: "common", horsepower: 180, country: "South Korea" },
  { make: "Kia", model: "Telluride", year: 2024, tier: "premium", horsepower: 291, country: "South Korea" },
  { make: "Kia", model: "Stinger", year: 2023, tier: "enthusiast", horsepower: 368, country: "South Korea" },
  { make: "Kia", model: "Pegas", year: 2024, tier: "common", horsepower: 95, country: "South Korea" },
  { make: "Mazda", model: "6", year: 2024, tier: "common", horsepower: 187, country: "Japan" },
  { make: "Mazda", model: "CX-90", year: 2024, tier: "premium", horsepower: 340, country: "Japan" },
  { make: "Mazda", model: "CX-5", year: 2024, tier: "common", horsepower: 187, country: "Japan" },

  // Chinese Brands in UAE
  { make: "Geely", model: "Monjaro", year: 2024, tier: "premium", horsepower: 235, country: "China" },
  { make: "Geely", model: "Coolray", year: 2024, tier: "common", horsepower: 177, country: "China" },
  { make: "Geely", model: "Emgrand", year: 2024, tier: "common", horsepower: 101, country: "China" },
  { make: "GAC", model: "GS8", year: 2024, tier: "premium", horsepower: 248, country: "China" },
  { make: "GAC", model: "Empow", year: 2024, tier: "enthusiast", horsepower: 177, country: "China" },
  { make: "Changan", model: "CS75 Plus", year: 2024, tier: "common", horsepower: 233, country: "China" },
  { make: "Changan", model: "UNI-K", year: 2024, tier: "premium", horsepower: 233, country: "China" },
  { make: "Changan", model: "UNI-V", year: 2024, tier: "enthusiast", horsepower: 185, country: "China" },
  { make: "Haval", model: "H6", year: 2024, tier: "common", horsepower: 201, country: "China" },
  { make: "Haval", model: "Dargo", year: 2024, tier: "enthusiast", horsepower: 211, country: "China" },
  { make: "Tank", model: "300", year: 2024, tier: "enthusiast", horsepower: 227, country: "China" },
  { make: "Tank", model: "500", year: 2024, tier: "premium", horsepower: 349, country: "China" },
  { make: "Jetour", model: "T2", year: 2024, tier: "enthusiast", horsepower: 254, country: "China" },
  { make: "Jetour", model: "Dashing", year: 2024, tier: "common", horsepower: 197, country: "China" },
  { make: "BYD", model: "Seal", year: 2024, tier: "enthusiast", horsepower: 523, country: "China" },
  { make: "BYD", model: "Han", year: 2024, tier: "premium", horsepower: 509, country: "China" },
  { make: "BYD", model: "Tang", year: 2024, tier: "premium", horsepower: 509, country: "China" },
  { make: "BYD", model: "Atto 3", year: 2024, tier: "common", horsepower: 201, country: "China" },
  { make: "Hongqi", model: "H9", year: 2024, tier: "exotic", horsepower: 283, country: "China" },
  { make: "Hongqi", model: "E-HS9", year: 2024, tier: "exotic", horsepower: 551, country: "China" },

  // Dubai Supercars & Exotics
  { make: "Maserati", model: "Ghibli", year: 2024, tier: "exotic", horsepower: 424, country: "Italy" },
  { make: "Maserati", model: "Levante", year: 2024, tier: "exotic", horsepower: 424, country: "Italy" },
  { make: "Maserati", model: "MC20", year: 2024, tier: "exotic", horsepower: 621, country: "Italy" },
  { make: "Maserati", model: "Grecale", year: 2024, tier: "premium", horsepower: 300, country: "Italy" },
  { make: "Lotus", model: "Emira", year: 2024, tier: "exotic", horsepower: 400, country: "UK" },
  { make: "Lotus", model: "Eletre", year: 2024, tier: "exotic", horsepower: 603, country: "UK" },
  { make: "Aston Martin", model: "DBX707", year: 2024, tier: "exotic", horsepower: 697, country: "UK" },
  { make: "Aston Martin", model: "Vantage", year: 2024, tier: "exotic", horsepower: 656, country: "UK" },
  { make: "Aston Martin", model: "DBS", year: 2023, tier: "unicorn", horsepower: 715, country: "UK" },
  { make: "Lamborghini", model: "Revuelto", year: 2024, tier: "unicorn", horsepower: 1001, country: "Italy" },
  { make: "Ferrari", model: "Purosangue", year: 2024, tier: "unicorn", horsepower: 715, country: "Italy" },
  { make: "Ferrari", model: "Roma", year: 2024, tier: "exotic", horsepower: 612, country: "Italy" },
  { make: "Ferrari", model: "296 GTB", year: 2024, tier: "exotic", horsepower: 819, country: "Italy" },
  { make: "Porsche", model: "911 GT3 RS", year: 2024, tier: "unicorn", horsepower: 518, country: "Germany" },
  { make: "Porsche", model: "Cayenne Turbo GT", year: 2024, tier: "exotic", horsepower: 650, country: "Germany" },
];
